# Generated by Django 5.2.3 on 2025-06-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this analysis', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this analysis')),
                ('start_date', models.DateField(help_text='Start date for analysis period')),
                ('end_date', models.DateField(help_text='End date for analysis period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Analysis',
                'verbose_name_plural': 'Time Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Date for this day's analysis")),
                ('sentiment', models.FloatField(help_text='Sentiment score from -1.0 (negative) to 1.0 (positive)')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages analyzed for this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='djangoapp.timeanalysis')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'ordering': ['date'],
                'unique_together': {('time_analysis', 'date')},
            },
        ),
    ]
