# Generated by Django 5.2.3 on 2025-06-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='sentiment',
            field=models.FloatField(help_text='Average sentiment score from -1.0 (negative) to 1.0 (positive)'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The message text')),
                ('sentiment', models.FloatField(help_text='Sentiment score from -1.0 (negative) to 1.0 (positive)')),
                ('source', models.CharField(choices=[('iMessage', 'iMessage'), ('WhatsApp', 'WhatsApp'), ('Gmail', 'Gmail')], help_text='Source of the message', max_length=20)),
                ('contact', models.CharField(blank=True, help_text='Contact or recipient', max_length=200)),
                ('timestamp', models.CharField(blank=True, help_text='Original timestamp from source', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='djangoapp.day')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sentiment'],
            },
        ),
    ]
