# Generated by Django 5.2.3 on 2025-06-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Activity type (walking, driving, stationary, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the location', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, help_text='Named location', max_length=200, null=True),
        ),
    ]
