# Generated by Django 5.2.3 on 2025-06-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_location_activity_type_alter_location_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-visit_count'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='location',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='source',
        ),
        migrations.RemoveField(
            model_name='location',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='location',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='location',
            name='activity_types',
            field=models.JSONField(default=dict, help_text='Activity types and their counts at this location'),
        ),
        migrations.AddField(
            model_name='location',
            name='center_latitude',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Center latitude of clustered GPS points', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='center_longitude',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Center longitude of clustered GPS points', max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='first_visit',
            field=models.DateTimeField(blank=True, help_text='First recorded visit to this location', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_visit',
            field=models.DateTimeField(blank=True, help_text='Last recorded visit to this location', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text='Name or description of this location', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent at this location in minutes'),
        ),
        migrations.AddField(
            model_name='location',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of GPS points in this cluster'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Address of this location', null=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
