# Generated by Django 5.2.3 on 2025-06-22 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_remove_location_place_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Website domain', max_length=200)),
                ('correlation_coefficient', models.FloatField(help_text='Correlation coefficient between website visits and sentiment scores')),
                ('days_visited', models.PositiveIntegerField(help_text='Number of days the website was visited')),
                ('days_not_visited', models.PositiveIntegerField(help_text='Number of days the website was not visited')),
                ('avg_sentiment_when_visited', models.FloatField(help_text='Average sentiment score when the website was visited')),
                ('avg_sentiment_when_not_visited', models.FloatField(help_text='Average sentiment score when the website was not visited')),
                ('total_visits', models.PositiveIntegerField(help_text='Total number of visits to the website')),
                ('significance_score', models.FloatField(help_text='Significance score of the correlation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_analyses', to='djangoapp.timeanalysis')),
            ],
            options={
                'verbose_name': 'Website Analysis',
                'verbose_name_plural': 'Website Analyses',
                'ordering': ['-correlation_coefficient'],
            },
        ),
    ]
