# Generated by Django 5.2.3 on 2025-06-22 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_websiteanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Contact or person name', max_length=200)),
                ('correlation_coefficient', models.FloatField(help_text='Correlation coefficient between interactions with this person and sentiment scores')),
                ('days_interacted', models.PositiveIntegerField(help_text='Number of days you interacted with this person')),
                ('days_not_interacted', models.PositiveIntegerField(help_text='Number of days you did not interact with this person')),
                ('avg_sentiment_when_interacted', models.FloatField(help_text='Average sentiment score when you interacted with this person')),
                ('avg_sentiment_when_not_interacted', models.FloatField(help_text='Average sentiment score when you did not interact with this person')),
                ('total_messages', models.PositiveIntegerField(help_text='Total number of messages exchanged with this person')),
                ('significance_score', models.FloatField(help_text='Significance score of the correlation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_analyses', to='djangoapp.timeanalysis')),
            ],
            options={
                'verbose_name': 'Person Analysis',
                'verbose_name_plural': 'Person Analyses',
                'ordering': ['-correlation_coefficient'],
            },
        ),
    ]
