# Generated by Django 5.2.3 on 2025-06-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_personanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteanalysis',
            name='example_url',
            field=models.URLField(blank=True, help_text='Example URL from this domain', max_length=500),
        ),
    ]
