# Generated by Django 5.2.3 on 2025-06-22 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_websiteanalysis_example_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_coefficient', models.FloatField(help_text='Correlation coefficient between being at this place and sentiment scores')),
                ('days_present', models.PositiveIntegerField(help_text='Number of days you were present at this place')),
                ('days_not_present', models.PositiveIntegerField(help_text='Number of days you were not present at this place')),
                ('avg_sentiment_when_present', models.FloatField(help_text='Average sentiment score when you were at this place')),
                ('avg_sentiment_when_not_present', models.FloatField(help_text='Average sentiment score when you were not at this place')),
                ('total_visits', models.PositiveIntegerField(help_text='Total number of visits to this place')),
                ('significance_score', models.FloatField(help_text='Significance score of the correlation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text='The location this analysis refers to', on_delete=django.db.models.deletion.CASCADE, to='djangoapp.location')),
                ('time_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_analyses', to='djangoapp.timeanalysis')),
            ],
            options={
                'verbose_name': 'Place Analysis',
                'verbose_name_plural': 'Place Analyses',
                'ordering': ['-correlation_coefficient'],
            },
        ),
    ]
